-- Tabla para almacenar los avisos del cronograma y que persistan
CREATE TABLE IF NOT EXISTS avisos_cronograma (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  dia TEXT NOT NULL,
  hora TEXT NOT NULL,
  fecha DATE NOT NULL
);

ALTER TABLE avisos_cronograma DISABLE ROW LEVEL SECURITY;
